---
repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: 47.6.1
  values:
  - test: test
